<?php

/**
 * Retries only the terms missing from product_images.php (e.g. ones that
 * hit Wikipedia's rate limit on the first pass), with a slower, backing-off
 * request pace. Merges newly resolved images into the existing file.
 */

$terms = require __DIR__ . '/fetch_terms.php';

$existing = file_exists(__DIR__ . '/product_images.php')
    ? require __DIR__ . '/product_images.php'
    : [];

$missing = array_diff_key($terms, $existing);
$total = count($missing);
$i = 0;

echo "Retrying {$total} missing keys...\n";

foreach ($missing as $key => $title) {
    $i++;
    $url = 'https://en.wikipedia.org/api/rest_v1/page/summary/' . rawurlencode(str_replace(' ', '_', $title));

    $imageUrl = null;
    $attempts = 0;

    while ($attempts < 4) {
        $attempts++;

        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 15,
            CURLOPT_HTTPHEADER => ['User-Agent: NavsonsSeederImageFetch/1.0 (dev@localhost; contact via repo owner)'],
            CURLOPT_SSL_VERIFYPEER => true,
        ]);
        $body = curl_exec($ch);
        $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if ($status === 200 && $body) {
            $data = json_decode($body, true);
            $imageUrl = $data['originalimage']['source'] ?? $data['thumbnail']['source'] ?? null;
            break;
        }

        if ($status === 429) {
            $wait = 3 * $attempts;
            echo "  rate limited on {$key}, waiting {$wait}s (attempt {$attempts})...\n";
            sleep($wait);
            continue;
        }

        // other error (404 etc.) - no point retrying
        break;
    }

    if ($imageUrl) {
        $existing[$key] = $imageUrl;
        echo "[{$i}/{$total}] OK    {$key} => {$title}\n";
    } else {
        echo "[{$i}/{$total}] MISS  {$key} => {$title} (status {$status})\n";
    }

    usleep(800000);
}

ksort($existing);
$export = "<?php\n\n// Auto-generated by fetch_product_images.php / retry_product_images.php — do not edit by hand.\n// image_key => real photo URL (Wikimedia Commons, via Wikipedia REST summary API).\nreturn " . var_export($existing, true) . ";\n";

file_put_contents(__DIR__ . '/product_images.php', $export);

echo "\nDone. Total resolved: " . count($existing) . "/" . (count($existing) + count(array_diff_key($terms, $existing))) . "\n";
